Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# get the path to a specific zarr store (the last one from the dataframe above)
zstore = df_ta_ncar.zstore.values[-1]
print(zstore)

# create a mutable-mapping-style interface to the store
mapper = fsspec.get_mapper(zstore)

# open it using xarray and zarr
ds = xr.open_zarr(mapper, consolidated=True)
ds
------------------

----- stdout -----
gs://cmip6/CMIP6/CMIP/NCAR/CESM2-FV2/historical/r2i1p1f1/Amon/tas/gn/v20200226/
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 6[0m
[1;32m      3[0m [38;5;28mprint[39m(zstore)
[1;32m      5[0m [38;5;66;03m# create a mutable-mapping-style interface to the store[39;00m
[0;32m----> 6[0m mapper [38;5;241m=[39m [43mfsspec[49m[38;5;241;43m.[39;49m[43mget_mapper[49m[43m([49m[43mzstore[49m[43m)[49m
[1;32m      8[0m [38;5;66;03m# open it using xarray and zarr[39;00m
[1;32m      9[0m ds [38;5;241m=[39m xr[38;5;241m.[39mopen_zarr(mapper, consolidated[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/fsspec/mapping.py:245[0m, in [0;36mget_mapper[0;34m(url, check, create, missing_exceptions, alternate_root, **kwargs)[0m
[1;32m    214[0m [38;5;250m[39m[38;5;124;03m"""Create key-value interface for given URL and options[39;00m
[1;32m    215[0m 
[1;32m    216[0m [38;5;124;03mThe URL will be of the form "protocol://location" and point to the root[39;00m
[0;32m   (...)[0m
[1;32m    242[0m [38;5;124;03m``FSMap`` instance, the dict-like key-value store.[39;00m
[1;32m    243[0m [38;5;124;03m"""[39;00m
[1;32m    244[0m [38;5;66;03m# Removing protocol here - could defer to each open() on the backend[39;00m
[0;32m--> 245[0m fs, urlpath [38;5;241m=[39m [43murl_to_fs[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    246[0m root [38;5;241m=[39m alternate_root [38;5;28;01mif[39;00m alternate_root [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m urlpath
[1;32m    247[0m [38;5;28;01mreturn[39;00m FSMap(root, fs, check, create, missing_exceptions[38;5;241m=[39mmissing_exceptions)

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/fsspec/core.py:388[0m, in [0;36murl_to_fs[0;34m(url, **kwargs)[0m
[1;32m    386[0m     inkwargs[[38;5;124m"[39m[38;5;124mfo[39m[38;5;124m"[39m] [38;5;241m=[39m urls
[1;32m    387[0m urlpath, protocol, _ [38;5;241m=[39m chain[[38;5;241m0[39m]
[0;32m--> 388[0m fs [38;5;241m=[39m [43mfilesystem[49m[43m([49m[43mprotocol[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43minkwargs[49m[43m)[49m
[1;32m    389[0m [38;5;28;01mreturn[39;00m fs, urlpath

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/fsspec/registry.py:289[0m, in [0;36mfilesystem[0;34m(protocol, **storage_options)[0m
[1;32m    282[0m     warnings[38;5;241m.[39mwarn(
[1;32m    283[0m         [38;5;124m"[39m[38;5;124mThe [39m[38;5;124m'[39m[38;5;124marrow_hdfs[39m[38;5;124m'[39m[38;5;124m protocol has been deprecated and will be [39m[38;5;124m"[39m
[1;32m    284[0m         [38;5;124m"[39m[38;5;124mremoved in the future. Specify it as [39m[38;5;124m'[39m[38;5;124mhdfs[39m[38;5;124m'[39m[38;5;124m.[39m[38;5;124m"[39m,
[1;32m    285[0m         [38;5;167;01mDeprecationWarning[39;00m,
[1;32m    286[0m     )
[1;32m    288[0m [38;5;28mcls[39m [38;5;241m=[39m get_filesystem_class(protocol)
[0;32m--> 289[0m [38;5;28;01mreturn[39;00m [38;5;28;43mcls[39;49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mstorage_options[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/fsspec/spec.py:79[0m, in [0;36m_Cached.__call__[0;34m(cls, *args, **kwargs)[0m
[1;32m     77[0m     [38;5;28;01mreturn[39;00m [38;5;28mcls[39m[38;5;241m.[39m_cache[token]
[1;32m     78[0m [38;5;28;01melse[39;00m:
[0;32m---> 79[0m     obj [38;5;241m=[39m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__call__[39;49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m     80[0m     [38;5;66;03m# Setting _fs_token here causes some static linters to complain.[39;00m
[1;32m     81[0m     obj[38;5;241m.[39m_fs_token_ [38;5;241m=[39m token

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/gcsfs/core.py:269[0m, in [0;36mGCSFileSystem.__init__[0;34m(self, project, access, token, block_size, consistency, cache_timeout, secure_serialize, check_connection, requests_timeout, requester_pays, asynchronous, loop, callback_timeout, **kwargs)[0m
[1;32m    267[0m [38;5;28mself[39m[38;5;241m.[39mcallback_timeout [38;5;241m=[39m callback_timeout
[1;32m    268[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m asynchronous:
[0;32m--> 269[0m     [38;5;28mself[39m[38;5;241m.[39m_session [38;5;241m=[39m [43msync[49m[43m([49m
[1;32m    270[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloop[49m[43m,[49m[43m [49m[43mget_client[49m[43m,[49m[43m [49m[43mcallback_timeout[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcallback_timeout[49m
[1;32m    271[0m [43m    [49m[43m)[49m
[1;32m    272[0m     weakref[38;5;241m.[39mfinalize([38;5;28mself[39m, sync, [38;5;28mself[39m[38;5;241m.[39mloop, [38;5;28mself[39m[38;5;241m.[39msession[38;5;241m.[39mclose)
[1;32m    273[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/fsspec/asyn.py:103[0m, in [0;36msync[0;34m(loop, func, timeout, *args, **kwargs)[0m
[1;32m    101[0m     [38;5;28;01mraise[39;00m FSTimeoutError [38;5;28;01mfrom[39;00m [38;5;21;01mreturn_result[39;00m
[1;32m    102[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(return_result, [38;5;167;01mBaseException[39;00m):
[0;32m--> 103[0m     [38;5;28;01mraise[39;00m return_result
[1;32m    104[0m [38;5;28;01melse[39;00m:
[1;32m    105[0m     [38;5;28;01mreturn[39;00m return_result

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/fsspec/asyn.py:56[0m, in [0;36m_runner[0;34m(event, coro, result, timeout)[0m
[1;32m     54[0m     coro [38;5;241m=[39m asyncio[38;5;241m.[39mwait_for(coro, timeout[38;5;241m=[39mtimeout)
[1;32m     55[0m [38;5;28;01mtry[39;00m:
[0;32m---> 56[0m     result[[38;5;241m0[39m] [38;5;241m=[39m [38;5;28;01mawait[39;00m coro
[1;32m     57[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m ex:
[1;32m     58[0m     result[[38;5;241m0[39m] [38;5;241m=[39m ex

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/fsspec/implementations/http.py:28[0m, in [0;36mget_client[0;34m(**kwargs)[0m
[1;32m     27[0m [38;5;28;01masync[39;00m [38;5;28;01mdef[39;00m [38;5;21mget_client[39m([38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m---> 28[0m     [38;5;28;01mreturn[39;00m [43maiohttp[49m[38;5;241;43m.[39;49m[43mClientSession[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mTypeError[0m: ClientSession.__init__() got an unexpected keyword argument 'callback_timeout'

